/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @example 12345678 */
                        noteUserId: number;
                        noteNickName: string;
                        noteUrlName: string;
                    };
                };
            };
            responses: {
                /** @description ユーザーの作成に成功しました */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                /** @description ユーザーの作成に失敗しました */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 認証に失敗しました */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description サーバーエラーが発生しました */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 指定したIDのユーザーの取得に成功しました */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                /** @description リクエストが不正です */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 指定したIDのユーザーが見つかりませんでした */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description サーバーエラーが発生しました */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /**
                         * Format: date-time
                         * @example 2023-01-01T00:00:00.000Z
                         */
                        lastNoteCalculatedAt: string;
                    };
                };
            };
            responses: {
                /** @description ユーザー情報の更新に成功しました */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                /** @description ユーザー情報の更新に失敗しました */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 認証に失敗しました */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description サーバーエラーが発生しました */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description リクエストしたユーザーの記事の取得に成功しました */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            articles: {
                                /** @example 123456789 */
                                id: number;
                                /** @example n12345abcdef */
                                key: string;
                                title: string;
                                /**
                                 * Format: date-time
                                 * @example 2023-01-01T00:00:00.000Z
                                 */
                                publishedAt: string;
                            }[];
                        };
                    };
                };
                /** @description リクエストが不正です */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 認証に失敗しました */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description サーバーエラーが発生しました */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/articles/{noteArticleId}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    noteArticleId: number | null;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 指定したIDの記事の統計情報を取得に成功しました */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            article: {
                                title: string;
                                key: string;
                                /** Format: date-time */
                                publishedAt: string;
                            };
                            stats: {
                                readCount: number;
                                likeCount: number;
                                commentCount: number;
                                /** Format: date-time */
                                fetchedAt: string;
                            }[];
                        };
                    };
                };
                /** @description リクエストが不正です */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 指定したIDの記事が見つかりませんでした */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description サーバーエラーが発生しました */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    noteArticleId: number | null;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        article: {
                            title: string;
                            /** @example n12345abcdef */
                            key: string;
                            /**
                             * Format: date-time
                             * @example 2023-01-01T00:00:00.000Z
                             */
                            publishedAt: string;
                        };
                        stats: {
                            readCount: number;
                            likeCount: number;
                            commentCount: number;
                            /**
                             * Format: date-time
                             * @example 2023-01-01T00:00:00.000Z
                             */
                            fetchedAt: string;
                        };
                    };
                };
            };
            responses: {
                /** @description 統計情報の作成に成功しました */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            article: {
                                title: string;
                                key: string;
                                /** Format: date-time */
                                publishedAt: string;
                            };
                            stats: {
                                readCount: number;
                                likeCount: number;
                                commentCount: number;
                                /** Format: date-time */
                                fetchedAt: string;
                            };
                        };
                    };
                };
                /** @description 統計情報の作成に失敗しました */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 認証に失敗しました */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description サーバーエラーが発生しました */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    from?: string;
                    to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 統計の取得に成功しました */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                article: {
                                    title: string;
                                    key: string;
                                    /** Format: date-time */
                                    publishedAt: string;
                                };
                                stats: {
                                    readCount: number;
                                    likeCount: number;
                                    commentCount: number;
                                    /** Format: date-time */
                                    fetchedAt: string;
                                }[];
                            }[];
                        };
                    };
                };
                /** @description リクエストが不正です */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 認証に失敗しました */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description サーバーエラーが発生しました */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/stats/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 統計の取得に成功しました */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["DailyStats"][];
                        };
                    };
                };
                /** @description リクエストが不正です */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 認証に失敗しました */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description サーバーエラーが発生しました */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            /**
             * Format: uuid
             * @example 12345678-1234-1234-1234-1234567890ab
             */
            id: string;
            /** @example 12345678 */
            noteUserId: number;
            noteNickName: string;
            noteUrlName: string;
            /**
             * Format: date-time
             * @example 2023-01-01T00:00:00.000Z
             */
            lastNoteCalculatedAt: string;
        };
        DailyStats: {
            /** @example 2023-01-01 */
            date: string;
            totalReads: number;
            totalLikes: number;
            totalComments: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
